const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
const UPDATE_COURSES_SUCCESS = "UPDATE_COURSES_SUCCESS";
const CREATE_COURSES_SUCCESS = "CREATE_COURSES_SUCCESS";
const LOAD_AUTHOR_SUCCESS = "LOAD_AUTHOR_SUCCESS";
const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export default {
  LOAD_COURSES_SUCCESS,
  UPDATE_COURSES_SUCCESS,
  CREATE_COURSES_SUCCESS,
  LOAD_AUTHOR_SUCCESS,
  BEGIN_AJAX_CALL,
  AJAX_CALL_ERROR
};
